### ISSUE TITLE
Question about color layer?

### ISSUE THREAD

**Issue by crankler** [Ikhyeon-Cho/traversability#1]
Hi, it's a great work to learn the application of grid map, thanks for your share.
Can you tell me how to add the color layer, like ETH elevation mapping work.

**Comment by Ikhyeon-Cho** [comment]
Thanks for your comment! 

Currently, I've only tested this package on the LiDAR sensor (Velodyne and Ouster), so RGB pointclouds were not mainly considered. The traversability is determined on the basis of geometric attributes (like height, inclination angle, roughness, etc), so color layer was not needed. 

Integrating the color and semantics is our ongoing work and will be released soon after.

**Comment by fgmn** [comment]
@Ikhyeon-Cho Hi, any update on the color and semantics integration? Thank you!
